### ISSUE TITLE
!accept <notarealnickname> causes dongerdong to say the person won?

### ISSUE THREAD

**Issue by tonyravioli** [tonyravioli/dongerdong#13]
```
DEBUG:bearded-potato-donger::felda!~felda@192.183.97.2 PRIVMSG #donger :!accept nope
DEBUG:bearded-potato-donger:command: pubmsg, source: felda!~felda@192.183.97.2, target: #donger, arguments: ['!accept nope']
Unhandled exception in thread started by <bound method Donger._pubmsg of <__main__.Donger object at 0x1e1ac10>>
Traceback (most recent call last):
  File "./dongerdong.py", line 131, in _pubmsg
    cli.channels[self.chan].users[ev.splitd[1]]
KeyError: 'nope'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./dongerdong.py", line 134, in _pubmsg
    del self.pending[ev.splitd[1]]
KeyError: 'nope'
DEBUG:bearded-potato-donger:TO SERVER: PRIVMSG #donger :Err... Maybe you meant to say !fight nope? They never challenged you.
DEBUG:bearded-potato-donger:TO SERVER: PRIVMSG #donger :Well... They were cowards... YOU WIN
DEBUG:bearded-potato-donger::ravioli!~ravioli@unaffiliated/ravioli PRIVMSG #donger :wtf
```

**Comment by Polsaker** [comment]
Fixed by ravioli
