### ISSUE TITLE
lastedit probs

### ISSUE THREAD

**Issue by tonyravioli** [tonyravioli/dongerdong#60]
```
DEBUG:Donger:freenode:<< [ravioli!~ravioli@unaffiliated/ravioli] PRIVMSG ['#donger', '!stats']
ERROR:tornado.application:Future <pydle.async.Future object at 0x7fde264ba668> exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 3454, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such column: t1.lastedit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./dongerdong.py", line 647, in countStat
    stat = Stats.get(Stats.nick == nick)
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 4505, in get
    return sq.get()
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 2885, in get
    return next(clone.execute())
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 2932, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 2628, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 3461, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 3285, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 127, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 3454, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such column: t1.lastedit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 3454, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: UNIQUE constraint failed: stats.nick

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pydle/async.py", line 46, in wrapper
    gen = func(*args, **kwargs)
  File "./dongerdong.py", line 91, in on_message
    self.fight([source] + args, True if command == "deathmatch" else False, True if (command == "deathmatch" or command == "duel") else False)
  File "./dongerdong.py", line 609, in fight
    self.start(self.pendingFights[players[0].lower()])
  File "./dongerdong.py", line 460, in start
    self.countStat(pendingFight['players'][0], "fights")
  File "./dongerdong.py", line 651, in countStat
    praises=0, kills=0)
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 4494, in create
    inst.save(force_insert=True)
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 4680, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 3213, in execute
    cursor = self._execute()
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 2628, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 3461, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 3285, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 127, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/peewee.py", line 3454, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: UNIQUE constraint failed: stats.nick
```

**Comment by Polsaker** [comment]
I told you via irc how to add the new column to an already existing database

2016-04-20 19:40 GMT-03:00, Pasta Ravioli <notifications@github.com>:
