### ISSUE TITLE
Cancel doesn't work

### ISSUE THREAD

**Issue by tonyravioli** [tonyravioli/dongerdong#67]
```
DEBUG:Donger:freenode:<< [outside!~outside@removed.by.ravi] PRIVMSG ['#donger', '!duel ravioli']
DEBUG:Donger:freenode:<< [outside!~outside@removed.by.ravi] PRIVMSG ['#donger', '!cancel']
DEBUG:Donger:freenode:<< [outside!~outside@removed.by.ravi] PRIVMSG ['#donger', '!cancel ravioli']
DEBUG:Donger:freenode:<< [outside!~outside@removed.by.ravi] PRIVMSG ['#donger', 'rav, accept and watch']
DEBUG:Donger:freenode:<< [ravioli!~ravioli@unaffiliated/ravioli] PRIVMSG ['#donger', 'wat']
DEBUG:Donger:freenode:<< [ravioli!~ravioli@unaffiliated/ravioli] PRIVMSG ['#donger', '!accept outside ']
DEBUG:peewee:('SELECT "t1"."id", "t1"."nick", "t1"."wins", "t1"."losses", "t1"."kills", "t1"."quits", "t1"."idleouts", "t1"."fights", "t1"."accepts", "t1"."jo
ins", "t1"."praises" FROM "stats" AS t1 WHERE ("t1"."nick" = ?) LIMIT 1', ['outside'])
DEBUG:peewee:('UPDATE "stats" SET "fights" = ? WHERE ("stats"."nick" = ?)', [45, 'outside'])
ERROR:tornado.application:Future <pydle.async.Future object at 0x7f23428c2ef0> exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pydle/async.py", line 46, in wrapper
    gen = func(*args, **kwargs)
  File "./dongerdong.py", line 201, in on_message
    del self.pendingFights[args[0].lower()]
IndexError: list index out of range
DEBUG:peewee:('SELECT "t1"."id", "t1"."nick", "t1"."wins", "t1"."losses", "t1"."kills", "t1"."quits", "t1"."idleouts", "t1"."fights", "t1"."accepts", "t1"."jo
ins", "t1"."praises" FROM "stats" AS t1 WHERE ("t1"."nick" = ?) LIMIT 1', ['ravioli'])
DEBUG:peewee:('UPDATE "stats" SET "accepts" = ? WHERE ("stats"."nick" = ?)', [3, 'ravioli'])
```
Then a fight starts.

Here's lines 198-203:
```
                elif command == "cancel" and not self.gameRunning:
                    self.message(target, "Fight cancelled.")
                    try:
                        del self.pendingFights[args[0].lower()]
                    except KeyError:
                        self.message(target, "You can only !cancel if you started a fight.")
```
It looks like !reject works differently (it does ` self.pendingFights[args[0].lower()]['pendingaccept'].remove(source.lower())`), and I'm not sure why it's so much different.

**Comment by tonyravioli** [comment]
Should that be `del self.pendingFights[source.lower()]`?
